# Generated by Django 5.1 on 2025-11-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('tipo_membresia', models.CharField(max_length=100)),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
    ]
